import { useCallback, useEffect, useState, type FormEvent } from "react";
import { useNavigate } from "react-router-dom";
import { useTenantAuth } from "@/app/TenantAuthContext";
import { ApiError, apiBlobRequest, apiRequest, getApiErrorMessage } from "@/lib/api";
import { formatCurrency, formatDateTime } from "@/lib/formatters";

type Invoice = { id: string; type: "INVOICE"|"CREDIT_NOTE"; source: string; status: string; amount: number; currency: string; customer: string|null; cae: string|null; cbteNro: string|null; error: string|null; createdAt: string; creditNotes: Array<{id:string;status:string;cbteNro:string|null}> };
type Response = { items: Invoice[]; pagination: { total: number } };
type Settings = { mode: "automatic"|"confirmation"; policy: { entitlements?: Record<string,boolean> } | null };

export function ClientInvoicesPage() {
  const navigate = useNavigate(); const { invalidateSession, token, user } = useTenantAuth();
  const [items,setItems]=useState<Invoice[]>([]); const [settings,setSettings]=useState<Settings|null>(null); const [isLoading,setIsLoading]=useState(true); const [pending,setPending]=useState<string|null>(null); const [error,setError]=useState("");
  const [manual,setManual]=useState({amount:"",customer:"",customerDocType:"CUIT",customerDocNumber:""}); const [cancelId,setCancelId]=useState<string|null>(null); const [confirmation,setConfirmation]=useState("");
  const [scheduleId,setScheduleId]=useState<string|null>(null); const [issueAt,setIssueAt]=useState("");
  const unauthorized=useCallback(()=>{invalidateSession();navigate("/portal-cliente/login",{replace:true});},[invalidateSession,navigate]);
  const load=useCallback(async()=>{if(!token)return;setIsLoading(true);setError("");try{const [list,current]=await Promise.all([apiRequest<Response>("/portal/invoices?pageSize=100",{token,skipAuthHandling:true}),apiRequest<Settings>("/portal/invoices/settings",{token,skipAuthHandling:true})]);setItems(list.items);setSettings(current);}catch(e){if(e instanceof ApiError&&e.status===401)return unauthorized();setError(getApiErrorMessage(e,"No se pudieron cargar los comprobantes."));}finally{setIsLoading(false);}},[token,unauthorized]);
  useEffect(()=>{void load();},[load]);
  const entitlements=settings?.policy?.entitlements??{}; const canManage=user?.role==="owner"||user?.role==="admin"; const canConfirm=canManage||user?.role==="approver";
  async function action(path:string,id:string,body?:unknown){if(!token)return;setPending(id);setError("");try{await apiRequest(path,{method:"POST",token,skipAuthHandling:true,body});setCancelId(null);setConfirmation("");await load();}catch(e){if(e instanceof ApiError&&e.status===401)return unauthorized();setError(getApiErrorMessage(e,"No se pudo completar la accion."));}finally{setPending(null);}}
  async function createManual(event:FormEvent){event.preventDefault();await action("/portal/invoices/manual","manual",{...manual,amount:Number(manual.amount),currency:"ARS"});setManual({amount:"",customer:"",customerDocType:"CUIT",customerDocNumber:""});}
  async function changeMode(mode:"automatic"|"confirmation"){if(!token)return;setPending("settings");try{await apiRequest("/portal/invoices/settings",{method:"PUT",token,skipAuthHandling:true,body:{mode}});await load();}catch(e){setError(getApiErrorMessage(e,"No se pudo guardar la modalidad."));}finally{setPending(null);}}
  async function pdf(invoice:Invoice){if(!token)return;setPending(invoice.id);try{const blob=await apiBlobRequest(`/portal/invoices/${invoice.id}/pdf`,{token,skipAuthHandling:true});const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=`comprobante-${invoice.cbteNro??invoice.id}.pdf`;link.click();URL.revokeObjectURL(url);}catch(e){setError(getApiErrorMessage(e,"No se pudo descargar el PDF."));}finally{setPending(null);}}
  return <main className="client-main client-invoices-page"><header className="app-topbar"><div><strong>Comprobantes</strong><span>Facturas, confirmaciones y notas de credito de tu empresa.</span></div><button className="secondary-button" onClick={()=>void load()}>Actualizar</button></header>
    {error?<p className="form-error" role="alert">{error}</p>:null}
    <section className="panel client-invoice-settings"><div><strong>Modalidad para nuevas ventas POS</strong><p>La confirmacion evita emitir hasta que un usuario autorizado apruebe el comprobante.</p></div><select value={settings?.mode??"automatic"} disabled={!canManage||pending==="settings"} onChange={(e)=>void changeMode(e.target.value as "automatic"|"confirmation")}><option value="automatic">Automatica</option>{entitlements.clientApproval?<option value="confirmation">Con confirmacion</option>:null}</select></section>
    {canManage&&entitlements.manualInvoicing?<form className="panel client-manual-invoice" onSubmit={(e)=>void createManual(e)}><div className="section-subheading"><h2>Nueva factura manual</h2><p>La emision se procesa asincronicamente contra ARCA.</p></div><div className="client-profile-form__grid"><label className="field"><span>Importe *</span><input type="number" min="0.01" step="0.01" required value={manual.amount} onChange={e=>setManual(v=>({...v,amount:e.target.value}))}/></label><label className="field"><span>Cliente</span><input value={manual.customer} onChange={e=>setManual(v=>({...v,customer:e.target.value}))}/></label><label className="field"><span>Tipo documento</span><select value={manual.customerDocType} onChange={e=>setManual(v=>({...v,customerDocType:e.target.value}))}><option>CUIT</option><option>DNI</option><option>CONSUMIDOR_FINAL</option></select></label><label className="field"><span>Documento</span><input value={manual.customerDocNumber} onChange={e=>setManual(v=>({...v,customerDocNumber:e.target.value.replace(/\D/g,""),}))}/></label></div><button className="primary-button" disabled={pending==="manual"}>{pending==="manual"?"Creando...":"Crear y emitir"}</button></form>:null}
    <section className="section-table-card section-table-card--scrollable"><div className="section-table client-invoices-table"><div className="section-table__head"><span>Fecha</span><span>Comprobante</span><span>Origen</span><span>Cliente</span><span>Importe</span><span>Estado</span><span>Acciones</span></div>{isLoading?<div className="section-table__state">Cargando comprobantes...</div>:items.length?items.map(invoice=><div className="section-table__row" key={invoice.id}><span>{formatDateTime(invoice.createdAt)}</span><strong>{invoice.cbteNro??`${invoice.type==="CREDIT_NOTE"?"NC":"Factura"} ${invoice.id}`}</strong><span>{invoice.source}</span><span>{invoice.customer??"Consumidor final"}</span><span>{formatCurrency(invoice.amount)}</span><small className={`status-pill status-pill--${invoice.status==="ISSUED"?"success":invoice.status==="FAILED"?"danger":"warning"}`}>{invoice.status.replace(/_/g," ")}</small><span className="section-row-actions">{invoice.status==="PENDING_CONFIRMATION"&&canConfirm?<><button className="section-mini-button" disabled={pending===invoice.id} onClick={()=>void action(`/portal/invoices/${invoice.id}/confirm`,invoice.id)}>Emitir ahora</button><button className="section-mini-button" onClick={()=>setScheduleId(invoice.id)}>Programar</button></>:null}{invoice.status==="ISSUED"?<button className="section-mini-button" onClick={()=>void pdf(invoice)}>PDF</button>:null}{invoice.type==="INVOICE"&&invoice.status==="ISSUED"&&canManage&&entitlements.creditNotes&&!invoice.creditNotes.length?<button className="section-mini-button" onClick={()=>setCancelId(invoice.id)}>Anular</button>:null}</span>{scheduleId===invoice.id?<div className="client-invoice-cancel"><input type="datetime-local" value={issueAt} onChange={e=>setIssueAt(e.target.value)}/><button className="secondary-button" disabled={!issueAt||pending===invoice.id} onClick={()=>void action(`/portal/invoices/${invoice.id}/confirm`,invoice.id,{issueAt:new Date(issueAt).toISOString()})}>Confirmar horario</button></div>:null}{cancelId===invoice.id?<div className="client-invoice-cancel"><input value={confirmation} onChange={e=>setConfirmation(e.target.value)} placeholder="Escribi ANULAR"/><button className="secondary-button secondary-button--danger" disabled={confirmation!=="ANULAR"||pending===invoice.id} onClick={()=>void action(`/portal/invoices/${invoice.id}/credit-note`,invoice.id,{confirmation})}>Confirmar nota de credito</button></div>:null}</div>):<div className="section-table__state">No hay comprobantes.</div>}</div></section>
  </main>;
}
