import { useCallback, useEffect, useState } from "react";
import { useTenantAuth } from "@/app/TenantAuthContext";
import { apiRequest, getApiErrorMessage } from "@/lib/api";

type Billing = { status: "ACTIVE" | "PAST_DUE" | "CANCELED"; billingStatus: string | null; billingProvider: string | null; amount: number | null; currency: string | null; exchangeRate: number | null; exchangeRateAt: string | null; plan: { name: string; price: number; currency: string } };
export function ClientSubscriptionPage() {
  const { token, user } = useTenantAuth(); const [billing, setBilling] = useState<Billing | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const canManage = user?.role === "owner" || user?.role === "admin";
  const load = useCallback(async () => { if (!token) return; try { setBilling(await apiRequest<Billing>("/portal/subscription/billing", { token })); } catch (cause) { setError(getApiErrorMessage(cause)); } }, [token]);
  useEffect(() => { void load(); }, [load]);
  async function checkout() { if (!token) return; setBusy(true); setError(""); try { const result = await apiRequest<{ checkoutUrl: string }>("/portal/subscription/checkout", { method: "POST", token }); window.location.assign(result.checkoutUrl); } catch (cause) { setError(getApiErrorMessage(cause, "No se pudo iniciar el pago.")); setBusy(false); } }
  async function change(action: "pause" | "resume" | "cancel") { if (!token || !window.confirm(action === "cancel" ? "La cancelacion es definitiva. ¿Continuar?" : "¿Confirmas el cambio?")) return; setBusy(true); try { await apiRequest(`/portal/subscription/${action}`, { method: "POST", token }); await load(); } catch (cause) { setError(getApiErrorMessage(cause)); } finally { setBusy(false); } }
  return <main className="client-main"><header className="app-topbar"><div><strong>Plan y suscripcion</strong><span>Administra el debito mensual de Mercado Pago.</span></div></header>{error ? <p className="form-error" role="alert">{error}</p> : null}<section className="panel"><div className="section-subheading"><span className="eyebrow">Plan vigente</span><h2>{billing?.plan.name || "Cargando..."}</h2></div>{billing ? <div className="subscription-summary"><strong>{billing.plan.currency} {billing.plan.price} por mes</strong><p>El cobro se realiza en ARS al tipo vendedor billete del Banco Nacion.</p><span className={`status-pill status-pill--${billing.status === "ACTIVE" ? "success" : billing.status === "CANCELED" ? "danger" : "warning"}`}>{billing.status}</span>{billing.amount ? <p>Proximo importe configurado: {billing.currency} {billing.amount.toLocaleString("es-AR")} · cotizacion {billing.exchangeRate?.toLocaleString("es-AR")}</p> : null}<div className="marketing-actions">{canManage && !billing.billingStatus ? <button className="primary-button" disabled={busy} onClick={() => void checkout()}>Adherir tarjeta con Mercado Pago</button> : null}{canManage && billing.billingStatus === "paused" ? <button className="primary-button" disabled={busy} onClick={() => void change("resume")}>Reactivar</button> : null}{canManage && billing.billingStatus === "authorized" ? <button className="secondary-button" disabled={busy} onClick={() => void change("pause")}>Pausar</button> : null}{canManage && billing.status !== "CANCELED" && billing.billingStatus ? <button className="danger-button" disabled={busy} onClick={() => void change("cancel")}>Cancelar suscripcion</button> : null}</div></div> : null}</section></main>;
}
