import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { apiRequest } from "@/lib/api";

type Plan = { code: string; name: string; description: string | null; price: number | null; currency: string; policy: { entitlements?: Record<string, boolean> } };
const featureLabels: Record<string, string> = { automaticInvoicing: "Facturacion automatica desde Mercado Pago POS", pdfDownload: "Descarga de comprobantes PDF", clientApproval: "Confirmacion y emision diferida", creditNotes: "Notas de credito", manualInvoicing: "Facturacion manual", googleDriveSheets: "Google Drive y Sheets", ocrImport: "Carga asistida con OCR" };

export function LandingPage() {
  const [plans, setPlans] = useState<Plan[]>([]);
  useEffect(() => { void apiRequest<{ items: Plan[] }>("/public/plans").then((value) => setPlans(value.items)).catch(() => setPlans([])); }, []);
  return <main className="marketing-page">
    <nav className="marketing-nav"><Link to="/" className="marketing-brand">Facturador</Link><div><a href="#planes">Planes</a><Link to="/tutoriales">Tutoriales</Link><Link to="/portal-cliente/login">Ingresar</Link><Link className="primary-button" to="/registro">Comenzar</Link></div></nav>
    <section className="marketing-hero"><div><span className="eyebrow">Facturacion argentina, sin trabajo repetitivo</span><h1>De Mercado Pago POS a ARCA, con control y trazabilidad.</h1><p>Automatiza comprobantes, revisa excepciones y entrega PDFs desde un portal preparado para cada etapa de tu negocio.</p><div className="marketing-actions"><Link className="primary-button" to="/registro">Crear mi cuenta</Link><a className="secondary-button" href="#como-funciona">Como funciona</a></div></div><aside><strong>Un flujo ordenado</strong><ol><li>Detectamos tus ventas POS.</li><li>Emitimos o solicitamos confirmacion.</li><li>Generamos el PDF y registramos cada resultado.</li></ol></aside></section>
    <section id="como-funciona" className="marketing-section"><span className="eyebrow">Todo en un mismo lugar</span><h2>Crece desde la automatizacion esencial hasta operaciones avanzadas.</h2><div className="marketing-benefits"><article><h3>Seguro por tenant</h3><p>Credenciales, usuarios y datos separados por empresa.</p></article><article><h3>Operable</h3><p>Estados, errores y reintentos visibles, sin perder trazabilidad.</p></article><article><h3>Flexible</h3><p>Procesamiento inmediato, programado o con confirmacion segun el plan.</p></article></div></section>
    <section id="planes" className="marketing-section"><span className="eyebrow">Planes</span><h2>Elegí el nivel de automatizacion que necesitas.</h2><div className="marketing-plans">{plans.length ? plans.map((plan) => <article key={plan.code}><span>{plan.code.replace("TIER_", "Nivel ")}</span><h3>{plan.name}</h3><strong>{plan.price == null ? "Precio a confirmar" : new Intl.NumberFormat("es-AR", { style: "currency", currency: plan.currency }).format(plan.price)}</strong><p>{plan.description}</p><ul>{Object.entries(plan.policy.entitlements || {}).filter(([, enabled]) => enabled).map(([key]) => featureLabels[key] ? <li key={key}>{featureLabels[key]}</li> : null)}</ul><Link className="secondary-button" to={`/registro?plan=${plan.code}`}>Elegir plan</Link></article>) : <p>Estamos cargando los planes disponibles.</p>}</div></section>
    <section className="marketing-section"><span className="eyebrow">Preguntas frecuentes</span><h2>Lo importante antes de comenzar.</h2><div className="marketing-benefits"><article><h3>¿Opera directamente en produccion?</h3><p>No. Primero revisamos el perfil fiscal y las integraciones; la habilitacion queda auditada.</p></article><article><h3>¿Puedo descargar los comprobantes?</h3><p>Si. Todos los planes incluyen el PDF de cada comprobante emitido.</p></article><article><h3>¿Debo compartir contraseñas?</h3><p>No. El onboarding no solicita passwords, tokens ni certificados por texto libre.</p></article></div></section>
    <section className="marketing-cta"><h2>Empeza con una cuenta preparada para tu empresa.</h2><p>El alta crea tu espacio y te guia por la configuracion fiscal e integraciones.</p><Link className="primary-button" to="/registro">Registrarme</Link></section>
    <footer className="marketing-footer"><span>Facturador</span><Link to="/tutoriales">Centro de ayuda</Link><a href="mailto:contacto@facturador.app">Contacto</a></footer>
  </main>;
}
