import { useEffect, useState, type FormEvent } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { apiRequest, getApiErrorMessage } from "@/lib/api";

type Plan = { code: string; name: string; price: number | null; currency: string };
type Result = { tenantSlug: string; email: string; verificationRequired: boolean; billingStatus: string; verificationToken?: string };

export function RegisterPage() {
  const [params] = useSearchParams(); const [plans, setPlans] = useState<Plan[]>([]); const [result, setResult] = useState<Result | null>(null); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const [form, setForm] = useState({ businessName: "", slug: "", email: "", password: "", planCode: params.get("plan") || "TIER_1", acceptedTerms: false });
  useEffect(() => { void apiRequest<{ items: Plan[] }>("/public/plans").then((value) => setPlans(value.items)).catch(() => setError("No pudimos cargar los planes.")); }, []);
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); setError(""); try { setResult(await apiRequest<Result>("/public/register", { method: "POST", body: form })); } catch (cause) { setError(getApiErrorMessage(cause, "No pudimos crear la cuenta.")); } finally { setSaving(false); } }
  async function verify() { if (!result?.verificationToken) return; try { await apiRequest("/public/verify-contact", { method: "POST", body: { token: result.verificationToken } }); setResult({ ...result, verificationToken: undefined, verificationRequired: false }); } catch (cause) { setError(getApiErrorMessage(cause)); } }
  if (result) return <main className="public-form-page"><section className="public-form-card"><span className="eyebrow">Cuenta creada</span><h1>Verifica tu email para ingresar</h1><p>Tu empresa se creó como <strong>{result.tenantSlug}</strong>. La suscripcion permanecera pendiente hasta conectar el medio de cobro.</p>{result.verificationToken ? <button className="primary-button" onClick={() => void verify()}>Verificar email en desarrollo</button> : result.verificationRequired ? <p>Revisa el enlace enviado a {result.email}.</p> : <Link className="primary-button" to="/portal-cliente/login">Ingresar al portal</Link>}</section></main>;
  return <main className="public-form-page"><form className="public-form-card" onSubmit={(event) => void submit(event)}><Link to="/">← Volver</Link><span className="eyebrow">Alta autoservicio</span><h1>Crea el espacio de tu empresa</h1><label className="field"><span>Nombre comercial</span><input required maxLength={120} value={form.businessName} onChange={(e) => setForm({ ...form, businessName: e.target.value, slug: form.slug || e.target.value.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") })} /></label><label className="field"><span>Identificador para ingresar</span><input required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" value={form.slug} onChange={(e) => setForm({ ...form, slug: e.target.value.toLowerCase() })} /></label><label className="field"><span>Email del responsable</span><input required type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /></label><label className="field"><span>Password</span><input required minLength={8} type="password" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} /></label><label className="field"><span>Plan</span><select value={form.planCode} onChange={(e) => setForm({ ...form, planCode: e.target.value })}>{plans.map((plan) => <option key={plan.code} value={plan.code}>{plan.name}{plan.price == null ? " · precio a confirmar" : ` · ${plan.currency} ${plan.price}`}</option>)}</select></label><label className="public-consent"><input type="checkbox" checked={form.acceptedTerms} onChange={(e) => setForm({ ...form, acceptedTerms: e.target.checked })} /><span>Acepto los terminos de servicio y la politica de privacidad.</span></label>{error ? <p className="form-error" role="alert">{error}</p> : null}<button className="primary-button" disabled={saving}>{saving ? "Creando..." : "Crear cuenta"}</button></form></main>;
}
