ALTER TABLE "Plan" ADD COLUMN "price" DOUBLE PRECISION;
ALTER TABLE "Plan" ADD COLUMN "currency" TEXT NOT NULL DEFAULT 'ARS';
ALTER TABLE "Plan" ADD COLUMN "billingCycle" TEXT NOT NULL DEFAULT 'monthly';
ALTER TABLE "Plan" ADD COLUMN "status" TEXT NOT NULL DEFAULT 'ACTIVE';
ALTER TABLE "Plan" ADD COLUMN "description" TEXT;
